# Generated by Django 5.0.4 on 2024-04-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SanalAjanda', '0002_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.AlterField(
            model_name='task',
            name='not_metni',
            field=models.CharField(max_length=100),
        ),
    ]
