# Generated by Django 5.0.4 on 2024-04-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SanalAjanda', '0004_task_user_alter_task_not_metni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='not_metni',
            field=models.CharField(max_length=250),
        ),
    ]
