# Generated by Django 5.0.4 on 2024-04-07 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SanalAjanda', '0005_alter_task_not_metni'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Tasks',
        ),
    ]
