# Generated by Django 5.0.4 on 2024-04-08 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SanalAjanda', '0007_mailsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MailSettings',
        ),
    ]
