# Generated by Django 5.0.4 on 2024-04-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SanalAjanda', '0008_delete_mailsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
