# Generated by Django 5.0.4 on 2024-04-10 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SanalAjanda', '0009_alter_customuser_is_active'),
    ]

    operations = [
    ]
