# Generated by Django 5.0.4 on 2024-04-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SanalAjanda', '0010_auto_20240410_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='note_delivery_time',
            field=models.TimeField(default='21:00'),
        ),
    ]
