# Generated by Django 5.0.4 on 2024-04-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SanalAjanda', '0011_customuser_note_delivery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='automatic_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
